version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Strong_P@ssword"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  somecarapp:
    depends_on: [db]
    image: somecarapp
    build:
      context: .
      dockerfile: SomeCarApp/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
        - ConnectionStrings__CarsDB=Server=host.docker.internal,1433;Database=CarDB;Trusted_Connection=False;User Id=SA;Password=Strong_P@ssword;